spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anuraktidb
    username: root
    password: m@stermind16
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true